{% set version = "0.15.1b" %}

package:
  name: libmad
  version: {{ version }}

source:
  url: ftp://ftp.mars.org/pub/mpeg/libmad-{{ version }}.tar.gz
  sha256: bbfac3ed6bfbc2823d3775ebb931087371e142bb0e9bb1bee51a76a6e0078690
  patches:
    - libmad-{{ version }}-fixes-1.patch  # [not win]

build:
  number: 1001
  run_exports:
    # https://abi-laboratory.pro/tracker/timeline/libmad
    - {{ pin_subpackage("libmad", max_pin="x.x") }}

requirements:
  build:
    - cmake      # [win]
    - autoconf   # [unix]
    - automake   # [unix]
    - libtool    # [unix]
    - make       # [unix]
    - {{ compiler('c') }}
  host:
    - pkgconfig  # [not win]

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]
  commands:
    - test -f $PREFIX/lib/libmad${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/include/mad.h  # [not win]
    - if not exist %LIBRARY_LIB%\\libmad.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\libmad.dll exit 1  # [win]
    - if not exist %LIBRARY_INC%\\libmad\\mad.h exit 1  # [win]

about:
  home: http://www.underbit.com/products/mad/
  license: GPL-2.0-only
  license_file: COPYING
  summary: "MPEG audio decoder"
  description: |
    MAD is a high-quality MPEG audio decoder. It currently supports MPEG-1 and the MPEG-2
    extension to lower sampling frequencies, as well as the de facto MPEG 2.5 format. All
    three audio layers — Layer I, Layer II, and Layer III (i.e. MP3) — are fully implemented.
  doc_url: http://www.underbit.com/products/mad/
  dev_url: https://sourceforge.net/projects/mad/

extra:
  recipe-maintainers:
    - dschreij
    - h-vetinari
