travis:
  secure:
    BINSTAR_TOKEN: IAo/2kXLWqa5SPKC/AUAA/dVEfQLd95vM78qDAXiyq8Z6Y0pC9GOLDzGnWJYnTRVYcubWteBESbl3UsbuO2DccYyKespozrUdOj7LeYJyx2XO/X/Ml7OAWWUy7zBIBFJsnRmGhpTgb3AUS6qljFZlC9T77E9C3eaZZV9SnUGjcQDOCfVWIffr/U/RPCJbYbBBCIC7foKTSrkdf4SdNSWoA0PmcF0Fn/cVYZdIkFybLPQidxQUQqH/OoWCb01bm0l7qDXkoYBIE77MJUdtNbd1a+GEh1Zuyo9Rnn9NXR9DQ3UWY35fKGXkG7xeQEdjXSg0yJ/agkFZfH8jRv9NMx/VEPwWvdV7L0LB6QELVRKAAjS9otW9s/hPYgHPUAwNGUddXctrvHWk/fG8jC18Qn8lvWRtq6aFWoUYgtF1Zgi0NShHD/e7znk8p+h2B3usw5BchCmL/hiS6/mj090hQQb7c3JOlgOYsgkw27/hgS1KewVXDGSjBcxJ6nKKgK1EHG2aViPjJvR+cJ5jEIEDbI0qJldPZ+ypaDBZKZQKF8yvFezWw3LPP6Jx+h1AXtlCgXKLYzGrrXu8Itv7qV53icxD/mM4IMc8GeyUCRw0zldl2kONGHxI7aFhgTdsgHFQ6CBL2ya3ezBKtpCc/KBB+p7aKlXbvhGzwNPnPwyGkIeLGk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
