travis:
  secure:
    BINSTAR_TOKEN: mSG8wwbI1gGz0nkNgH6He0cKaZ8ci9Vv078qp0a/ss6N1HaagmhSiCAWQ9Tc26HQ7AW6lzwhJR7CEFq3NjpuSVlPQ2huAG0VrwjSmrlvd/x44vfZf3CYT9hvBayXhvHv8qHeGYQpPbv9XhQALZMP+MTkwkEOKC1SNLNICKA6cZvOQ2Ep3KerV5OLWKBq4xlFPwjXIsx6FCV9MOy7JAavmZZ7xLLRmP8t4R9mM4blpLKriymojzZ/5TVhlHpXUi3p9aRKcT7tp6xmuYiEpi6ajFse/axJo9bVddpG6Al4ry2VWec0zJzJrKPP3Ju6PvK4Arid+c9vJqFZJKeKdVgiZwMZbSTYaHuCMvKFZQJNwP92fBW2YIYl1zn6Ne6yCSP9etl8yaulXtV5l2g5G3xJ1ASq6t/5J6J9B909xFYkVmnkJYMmyeqB4L7v8MD+1WBuHU9nN/Zf+vH2OTGmHH76i+XLOOYN7bEV2r3gXWWLB0U5TbOoeoyusSWaTKUQj0ylBps1Ein5m334noLYUtGPRV2oPrzMm3NvB26FQAec5VtEPfYmWDqI/Nt0OYKusn5MDXQRBEw4kZCRsD6WXgA21nQxEnaSDH0cgGmu+Q050utnSLCOyDulpmPAzYH6s01+CzP79XveggshCmXOCHwzvuhAIhjstl8BuYqGsCE6kzY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
